### ISSUE TITLE
Docker - RaspberryPi build images 32bit and 64bit

### ISSUE THREAD

**Issue by natm** [natm/iocontrollergw#27]

**Comment by natm** [comment]
@korben66

**Comment by Korben66** [comment]
@natm I will wait impatiently for the update....

**Comment by natm** [comment]
Additional builds are now being published to Dockerhub:

- linux/arm/v6
- linux/arm/v7
- linux/arm64
- linux/386

**Comment by natm** [comment]
https://hub.docker.com/r/natmorris/iocontrollergw/tags
